function visualize(inputfile, indices, step, threshold, outputprefix)
% This script visualizes voxelized shapes generated by main.lua
% Arguments:
%   inputfile: the .mat file that saves voxelized shapes
%   indices: the indices of objects in the inputfile that should be rendered. 
%            The default value is 0, which stands for rendering all objects.
%   step (s): downsample objects via a max pooling of step s for efficiency.
%             The default value is 4 (64 x 64 x 64 -> 16 x 16 x 16).
%   threshold: voxels with confidence lower than the threshold are not displayed
%   outputprefix: when not specified, Matlab shows figures directly
%                 when specified, Matlab stores rendered images of objects at 
%                 'outputprefix_%i.bmp', where %i is the index of objects 

if ~exist('indices', 'var')
  indices = 0;
end
if ~exist('step', 'var')
  step = 4;
end
if ~exist('threshold', 'var')
  threshold = 0.1;
end
visibility = ~exist('outputprefix', 'var');

load(inputfile, 'voxels');
if isnumeric(indices) 
    if indices == 0
        indices = 1:size(voxels,1);
    end
end

for index = indices
    voxel = squeeze(voxels(index,:,:,:,:));
    fig = voxel_render(voxel, step, threshold, visibility);
    if ~visibility
        saveas(fig,[outputprefix '_' num2str(index) '.bmp']);
    end
end



